package global

var AWBAllowList = []string{"'zin is short for Tamzin",
	"*angys*",
	"-noah-",
	"-sche",
	"10mmsocket",
	"1234qwer1234qwer4",
	"1989",
	"1AmNobody24",
	"1brianm7",
	"1TWO3Writer",
	"25stargeneral",
	"2NumForIce",
	"2x2x2x2x2",
	"3602kiva",
	"3family6",
	"3PPYB6",
	"49p",
	"4TheWynne",
	"511KeV",
	"8rz",
	"97198",
	"99of9",
	"A ntv",
	"A Random Hylian",
	"A smart kitten",
	"A.sav",
	"A876",
	"Aadirulez8",
	"Aamuizz",
	"Aaron Liu",
	"AaronY",
	"AB-me",
	"Abeg92",
	"AbsoluteWissen",
	"Abyssal",
	"Acabashi",
	"ACB Smith",
	"Acebulf",
	"Acefitt",
	"Achim55",
	"Actualcpscm",
	"Adam Harangozó (LSE WiR)",
	"Adamiow",
	"Adamtt9",
	"Adavidb",
	"AdobongPogi",
	"Adrian J. Hunter",
	"Adrio",
	"Aeroid",
	"Aeschylus",
	"Afernand74",
	"AfroThundr3007730",
	"AG47",
	"Agradman",
	"Agusbou2015",
	"Ahmetlii",
	"AirshipJungleman29",
	"AjaxSmack",
	"AJona1992",
	"Ajraddatz",
	"Akaza",
	"Aknell4",
	"Akrabbim",
	"Alalch E.",
	"Alaney2k",
	"AlanM1",
	"Alanscottwalker",
	"Alansohn",
	"Alarics",
	"Aldaron",
	"AleatoryPonderings",
	"Alekjds",
	"Alessandro57",
	"Alex 21",
	"Alex Sims",
	"Alex Spade",
	"Alex43223",
	"Alexanderino",
	"Alexandermcnabb",
	"AlexandraAVX",
	"Alexiaa",
	"Alexiscoutinho",
	"Alextejthompson",
	"Alifazal",
	"Alistair1978",
	"AllCatsAreGrey",
	"Allecher",
	"Alon Alush",
	"AlphaMikeOmega",
	"Aluxosm",
	"Alyo",
	"AmaryllisGardener",
	"Amigao",
	"Amisom",
	"AMK152",
	"Ampimd",
	"Anastrophe",
	"Anaxial",
	"Andra Febrian",
	"Andrew Davidson",
	"Andrew nyr",
	"Andrew11374265",
	"Andrewman327",
	"AndrewRT",
	"Andrybak",
	"Andyross",
	"Andysmith248",
	"Animalparty",
	"Anne drew",
	"ANode",
	"Anomalocaris",
	"Anon423",
	"AntanO",
	"Antiqueight",
	"Anupam",
	"Anythingyouwant",
	"AP1787",
	"Aplucas0703",
	"Apmh",
	"AquaDTRS",
	"Aquillion",
	"Aranya",
	"Arcaist",
	"Arcrev1",
	"ArcticSeeress",
	"Aristophanes68",
	"AriTheHorse",
	"Arjunaraoc",
	"Armbrust",
	"Arx Fortis",
	"AshLin",
	"Aspects",
	"Assadzadeh",
	"Assem Khidhr",
	"AssumeGoodWraith",
	"AstrooKai",
	"Atchom",
	"Atlantic306",
	"Atsme",
	"Attilios",
	"Auntof6",
	"Auric",
	"AviationFreak",
	"AX29",
	"Axem Titanium",
	"AxG",
	"Aydoh8",
	"Ayenaee",
	"Aymatth2",
	"Aza24",
	"B.Zsolt",
	"B203GTB",
	"Baberoothless",
	"Babin Mew",
	"BaduFerreira",
	"Bagwe Neza",
	"Bait30",
	"Balajijagadesh",
	"Baldy Bill",
	"Balon Greyjoy",
	"Bamse",
	"Banaticus",
	"BarntToust",
	"Baseball Watcher",
	"Bazonka",
	"Bdijkstra",
	"Beardo",
	"Beatpoet",
	"Beeswaxcandle",
	"BegbertBiggs",
	"Belbury",
	"Bellowhead678",
	"Bender235",
	"Bendono",
	"Benlisquare",
	"BerryForPerpetuity",
	"BilledMammal",
	"BillFlis",
	"Billreid",
	"Bingobro",
	"Binksternet",
	"Bis-Serjetà?",
	"Bitmapped",
	"BlackJack",
	"Blainster",
	"Blaixx",
	"Blakegripling ph",
	"BlameRuiner",
	"BlasterOfHouses",
	"Blethering Scot",
	"Bluemask",
	"Bluerasberry",
	"BMACS1002",
	"Bobamnertiopsis",
	"Bobherry",
	"Boghog",
	"Boivie",
	"Bon courage",
	"BoonDock",
	"Bop34",
	"Boredintheevening",
	"Bovineboy2008",
	"Brainulator9",
	"Brandon Downes",
	"BrandonXLF",
	"Bravelake",
	"Bread Enthusiast",
	"Breaktheicees",
	"Breawycker",
	"Bri",
	"Brightgalrs",
	"Broccoli and Coffee",
	"Brojam",
	"Brossow",
	"BrotherGunk",
	"Brutaldeluxe",
	"Bsherr",
	"Bsoyka",
	"Btspurplegalaxy",
	"Buaidh",
	"Bubba73",
	"BubbaJoe123456",
	"Buffaboy",
	"Bulldog73",
	"Bullmoosebell",
	"Bunnypranav",
	"Buster7",
	"Butlerblog",
	"Buttons to Push Buttons",
	"C1614",
	"Caddyshack01",
	"Caiaffa",
	"Caldorwards4",
	"Callmemirela",
	"Calvinballing",
	"Calwatch",
	"Cambalachero",
	"Cameremote",
	"Cameron Scott",
	"Canary757",
	"Cannolis",
	"Canuckian89",
	"Capankajsmilyo",
	"Capmo",
	"CAPTAIN RAJU",
	"Careless hx",
	"Carn",
	"CaroleHenson",
	"Carwil",
	"CASSIOPEIA",
	"Catalyzzt",
	"Cathodography",
	"Catrìona",
	"Catsmoke",
	"Cb6",
	"Cbuckley",
	"Celia Homeford",
	"Certes",
	"CFA",
	"Cg2916",
	"CGP05",
	"Chaosdruid",
	"Charitwo",
	"Chenzw",
	"Cherkash",
	"Chess",
	"Chickenpox4dinner",
	"Chidananda Kampa",
	"Chininazu12",
	"Chirags",
	"Chlod",
	"ChloeDrowssap",
	"Chorchapu",
	"Choucas0",
	"Chowbok",
	"Chris Ssk",
	"Chris the speller",
	"Chrisjnelson",
	"Christian75",
	"Cielquiparle",
	"Cinderella157",
	"Citing",
	"Citobun",
	"CitroenLover",
	"Ck786",
	"ClaudineChionh",
	"Clayoquot",
	"Clog Wolf",
	"Closed Limelike Curves",
	"Cnbrb",
	"CNMall41",
	"Coastie43",
	"Cocoaguy",
	"Codename Noreste",
	"Coderzombie",
	"Codrinb",
	"Coffeeandcrumbs",
	"Coldupnorth",
	"Colonies Chris",
	"CommunityNotesContributor",
	"Compassionate727",
	"ComputerFreak34",
	"Conifer",
	"CookieMonster755",
	"Cooldudeseven7",
	"Cornellier",
	"Cosmia Nebula",
	"Countercheck",
	"Cowboygilbert",
	"Cpiral",
	"CptViraj",
	"Crafterstar",
	"Craigthebirder",
	"Crazynas",
	"Cremastra (JWB)",
	"Crestfalling",
	"Crowsnest",
	"Cs-wolves",
	"Cscott",
	"CTF83!",
	"Curb Safe Charmer",
	"Curlyquote",
	"Cutlass",
	"CutOffTies",
	"CWenger",
	"CX Zoom",
	"Cyclopaedic",
	"Cyfraw",
	"Cypp0847",
	"Cyrobyte",
	"Czarking0",
	"D.18th",
	"Daask",
	"Damac",
	"Dan Koehl",
	"Dan121377",
	"Dan653",
	"Danbloch",
	"Danhash",
	"Danidamiobi",
	"Danners430",
	"Danorton",
	"Danre98",
	"Danski454",
	"Dantheanimator",
	"DarkGlow",
	"DarmaniLink",
	"Darranc",
	"Darth Stabro",
	"DASonnenfeld",
	"Dave.Dunford",
	"Davejohnsan",
	"Davemck",
	"David Edgar",
	"David Straub",
	"David.moreno72",
	"David1010",
	"DavidBrooks",
	"DavidBrooks-AWB",
	"DavidCane",
	"Davykamanzi",
	"Dawkin Verbier",
	"Dawnseeker2000",
	"DaxServer",
	"DBD",
	"Dcflyer",
	"Dclemens1971",
	"Ddas",
	"Dead.rabbit",
	"Deltaspace42",
	"Delusion23",
	"DemonDays64",
	"Derek Andrews",
	"Destinyokhiria",
	"Deuterostome",
	"Dewey Finn",
	"Dewritech",
	"DFlhb",
	"Dgw",
	"DH85868993",
	"Dharmadhyaksha",
	"Dhoru 21",
	"Dhtwiki",
	"DickClarkMises",
	"Dillard421",
	"Dionysodorus",
	"DiscantX",
	"DisillusionedBitterAndKnackered",
	"Dismas",
	"Dissident93",
	"DiverDave",
	"Dlthewave",
	"Dog Oxide",
	"DogsBreakfast87",
	"Dolotta",
	"Donama",
	"DonCalo",
	"Doniago",
	"DopefishJustin",
	"Dps04",
	"Dr Gangrene",
	"DRAGON BOOSTER",
	"Drboisclair",
	"Drdisque",
	"Dream Focus",
	"Dream out loud",
	"Dresdnhope",
	"Dricherby",
	"DrNegative",
	"Dual Freq",
	"Dudek1337",
	"Dunkleosteus77",
	"Dwaipayanc",
	"Dwo",
	"Dxneo",
	"Dylan620",
	"Dylnuge",
	"Dziban303",
	"Eastfarthingan",
	"Eastlaw",
	"Eastmain",
	"EatingCarBatteries",
	"Ebe123",
	"Ebyabe",
	"EchetusXe",
	"EchidnaLives",
	"Econterms",
	"Ecourter",
	"Ed6767",
	"EdgeNavidad",
	"Edibobb",
	"Editorofthewiki",
	"Edwardx",
	"Eejit43",
	"EEMIV",
	"EF5",
	"Egghead06",
	"EggRoll97",
	"El Esses",
	"Electricmemory",
	"Elekhh",
	"Elias Ziade",
	"Elizabeth Linden Rahway",
	"Elkman",
	"Em-mustapha",
	"Eman235",
	"EmanWilm",
	"Emerald-wiki",
	"Emir of Wikipedia",
	"Emma Caroline",
	"Emufarmers",
	"Encyclopædius",
	"Engr. Smitty",
	"Engrigg22",
	"Enock4seth",
	"Enwebb",
	"EnzoTC",
	"EoRdE6",
	"Epolk",
	"Epìdosis",
	"Eraserhead1",
	"Eric0892",
	"Eric0928",
	"EricSerge",
	"Erik",
	"Erisie",
	"Ertoe",
	"Erutuon",
	"Esculenta",
	"Esiymbro",
	"Esprit15d",
	"Esrever",
	"Est. 2021",
	"Estopedist1",
	"Eteethan",
	"Ethanbas",
	"Etothepi",
	"Eugenia ioessa",
	"Eurocopter",
	"Evaxooooof25",
	"Evelyn Harthbrooke",
	"Evelyn Marie",
	"Eviolite",
	"Evolt",
	"Evrik",
	"Ex nihil",
	"Exec8",
	"Eyesnore",
	"Faceless Enemy",
	"Faendalimas",
	"Faizhaider",
	"Fakescientist8000",
	"Falcorian",
	"Fattonyni",
	"Fdssdf",
	"FeldBum",
	"Felida97",
	"Feminist",
	"Fgnievinski",
	"FifthFive",
	"Finavon",
	"Find bruce",
	"Finnusertop",
	"Firezzasd",
	"Fitindia",
	"FlightTime",
	"Floydian",
	"Flying Saucer",
	"FMecha",
	"FMSky",
	"Fob.schools",
	"Folkezoft",
	"Fordmadoxfraud",
	"Fork99",
	"FormalDude",
	"Fortek67",
	"Fourthords",
	"Fram",
	"Francis Flinch",
	"Francish7",
	"Frank0051",
	"FrB.TG",
	"Freakmighty",
	"Fredddie",
	"Freedom4U",
	"Frost",
	"Frostly",
	"Fru1tbat",
	"Funandtrvl",
	"Funnyfarmofdoom",
	"FuriousFreddy",
	"Fyrael",
	"Fyunck(click)",
	"GabeIglesia",
	"Gaia Octavia Agrippa",
	"Galactic-Radiance",
	"Galactikapedia",
	"GalStar",
	"Garchy",
	"Gareth Griffith-Jones",
	"Garsh2",
	"Garuda3",
	"Gary",
	"Gasheadsteve",
	"Gbawden",
	"GCarty",
	"Geardona",
	"GearsDatapacks",
	"Geeoharee",
	"Gene93k",
	"Generalissima",
	"GeneralPoxter",
	"Genericusername57",
	"GentlemanGhost",
	"George Al-Shami",
	"George Burgess",
	"George Ho",
	"GGOTCC",
	"GhostInTheMachine",
	"GhostOrchid35",
	"GhostRiver",
	"Gikü",
	"GiovanniSidwell",
	"Giraffedata",
	"Giuliotf",
	"GKFX",
	"Glane23",
	"Gnoeee",
	"GNozaki",
	"Godsy",
	"Gog the Mild",
	"GoingBatty",
	"GoldRomean",
	"Golem08",
	"Gommeh",
	"Gonnym",
	"GoPurpleNGold24",
	"Goszei",
	"Gotitbro",
	"Governor Sheng",
	"Gracefool",
	"Grafen",
	"Graham11",
	"Grapesurgeon",
	"GraziePrego",
	"GreaterPonce665",
	"Greenbörg",
	"GreenC",
	"Greenman",
	"Greenshed",
	"Grey Wanderer",
	"Grk1011",
	"Gronk Oz",
	"Grumpylawnchair",
	"GSS",
	"Guliolopez",
	"Gurkubondinn",
	"Guy Macon",
	"GünniX",
	"H005",
	"Habst",
	"Hack",
	"HAL333",
	"HalfOfAnOrange",
	"Ham II",
	"Hamiltonstone",
	"Hamimh2",
	"HandsomeBoy",
	"HapHaxion",
	"Happy5214",
	"Happysailor",
	"Hardyplants",
	"Harris7",
	"Harryb7",
	"Harrybrowne1986",
	"Harrz",
	"Hassocks5489",
	"Hawaiian717",
	"Hayman30",
	"Headbomb",
	"Headhitter",
	"HeartGlow30797",
	"Hebrides",
	"Hellknowz",
	"Hemmers",
	"HenryLi",
	"Herostratus",
	"HeyElliott",
	"HiB2Bornot2B",
	"HiDrNick",
	"HighKing",
	"Hike395",
	"Hilst",
	"Hintha",
	"History DMZ",
	"HistoryTheorist",
	"HKLionel",
	"Hmich176",
	"Hmlarson",
	"Hogyn Lleol",
	"Howard the Duck",
	"Htanaungg",
	"HTGS",
	"Htonl",
	"HueMan1",
	"Huggums537",
	"Hulmem",
	"Hurricane Noah",
	"HurricaneCovid",
	"HurricaneZeta",
	"HurricaneZeta alt",
	"Hushpuckena",
	"Huwmanbeing",
	"HwyNerd Mike",
	"Hydronium Hydroxide",
	"Hyperik",
	"I Am Andumé",
	"I am bad at usernames",
	"I enjoy sandwiches",
	"I2Overcome",
	"IagoQnsi",
	"Iaintfaking",
	"IAmChaos",
	"Ian (Wiki Ed)",
	"Ian Dalziel",
	"Ian Rose",
	"Iazyges",
	"Ibadibam",
	"Ibagli",
	"Ibrahim Husain Meraj",
	"IceWelder",
	"Idiosyncritic",
	"Idoghor Melody",
	"Ihardlythinkso",
	"IJohnKennady",
	"Ijon",
	"Iljhgtn",
	"Illusion Flame",
	"ImaginesTigers",
	"Imcdc",
	"ImperfectlyInformed",
	"ImprovedWikiImprovment",
	"Impru20",
	"Imzadi1979",
	"Indagate",
	"Indefatigable",
	"Indopug",
	"Ineuw",
	"InfernoHues",
	"InfiniteNexus",
	"Inks.LWC",
	"Innotata",
	"Insertcleverphrasehere",
	"IntentionallyDense",
	"Interstatefive",
	"Interstellarity",
	"Intforce",
	"Intgr",
	"Inu06",
	"InverseHypercube",
	"Invest in knowledge",
	"Inwind",
	"Inzessin",
	"Ion Soggo",
	"Ionmars10",
	"Ipatrol",
	"Ippantekina",
	"IrisKawling",
	"Irn",
	"Isaac Rabinovitch",
	"Isento",
	"Iskandar323",
	"Isochrone",
	"It is a wonderful world",
	"Ita140188",
	"Itcouldbepossible",
	"Itineris55",
	"Iune",
	"Iveagh Gardens",
	"IVORK",
	"IznoRepeat",
	"J Mo 101",
	"J. Lunau",
	"J36miles",
	"J947",
	"Jabberjaw",
	"Jack Frost",
	"Jacona",
	"JaJaWa",
	"Jake01756",
	"JakeR",
	"JalenBarks",
	"Jameboy",
	"James Allison",
	"JamesLuiz",
	"Jameslwoodward",
	"Jane023",
	"Jarble",
	"Jarekt",
	"Jasca Ducato",
	"Jason Rees",
	"JASpencer",
	"Jasper Deng",
	"Jay1279",
	"Jayhawker6",
	"Jc3s5h",
	"Jeff G.",
	"Jeffrey R. Clark",
	"Jeffro77",
	"JeffUK",
	"Jennica",
	"Jerodlycett",
	"Jerome Charles Potts",
	"Jessamyn",
	"Jetstreamer",
	"Jevansen",
	"JFG",
	"Jfhutson",
	"Jheald",
	"Jianhui67",
	"Jinerea",
	"JJPMaster",
	"JL 09",
	"Jm3",
	"Jmcgnh",
	"JMHamo",
	"Jncraton",
	"Jnestorius",
	"Jochem van Hees",
	"JocularJellyfish",
	"JoelleJay",
	"JoeNMLC",
	"Joeyconnick",
	"Joeykai",
	"Joeyvandernaald",
	"John",
	"John Broughton",
	"John of Reading",
	"John Quiggin",
	"Johnjbarton",
	"Jojalozzo",
	"Jon Kolbert",
	"Jonathan Deamer",
	"Jonathansammy",
	"JonKolbert",
	"Jonteemil",
	"Jordano53",
	"JordanTimothyJames",
	"Joriki",
	"Joshua Issac",
	"Josve05a",
	"Jpbrenna",
	"Jsydave",
	"Jts1882",
	"JTtheOG",
	"Julipero",
	"Junemoon19",
	"Junglenut",
	"Juno",
	"Jusdafax",
	"Just a generic username",
	"Justanothersgwikieditor",
	"JuxtaposedJacob",
	"Jwslubbock",
	"Jībanmṛta",
	"K kisses",
	"K Lepo",
	"Kaffet i halsen",
	"Kahtar",
	"Kailash29792",
	"Kaltenmeyer",
	"KamranMackey",
	"KarlFrei",
	"Karnataka",
	"Karst",
	"Katharineamy",
	"KathrynLybarger",
	"Kautilya3",
	"Kazamzam",
	"KCVelaga",
	"KDTW Flyer",
	"Keironoshea",
	"Keizers",
	"KelleyCook",
	"Ken Gallager",
	"KennethSweezy",
	"Kepler-1229b",
	"KerbHopper",
	"Kerry Raymond",
	"Kgf0",
	"Kierzek",
	"Killarnee",
	"Kinsio",
	"Kippenvlees1",
	"Kiwipete",
	"Klemen Kocjancic",
	"Kline",
	"KoA",
	"Kowal2701",
	"Kpgjhpjm",
	"Krakatoa",
	"Krishna Chaitanya Velaga",
	"Kspiers",
	"Ktin",
	"Ktkvtsh",
	"Kungming2",
	"Kwamikagami",
	"Kwekubo",
	"KyleRGiggs",
	"Lady3mlnm",
	"Largoplazo",
	"Larry Hockett",
	"LastAmen",
	"Launchballer",
	"Laura240406",
	"Lcawte",
	"Leela52452",
	"Legis",
	"Lemondoge",
	"Lennart97",
	"Lensovet",
	"LeoFrank",
	"Leoneix",
	"Lepricavark",
	"Lettler",
	"Levivich",
	"Lexiconaut",
	"Lexlex",
	"Lfstevens",
	"Liance",
	"Liandrei",
	"Lightoil",
	"LilHelpa",
	"Lincolning",
	"Lincolnite",
	"LindsayH",
	"Lion-hearted85",
	"Little Professor",
	"LittlePuppers",
	"LJF2019",
	"Lo2u",
	"Logan",
	"Lollipoplollipoplollipop",
	"LordRapture",
	"Loriendrew",
	"Losipov",
	"Lozleader",
	"Lp0 on fire",
	"LtPowers",
	"Lucas7yoshi",
	"LucasBrown",
	"Luigi Boy",
	"LukeSurl",
	"LuniZunie",
	"Lwalt",
	"Lyndaship",
	"M-alt-azarian",
	"M.O.X",
	"Macaw*",
	"Macrakis",
	"Mad Mismagius",
	"Madcoverboy",
	"Maddy from Celeste",
	"Magiciandude",
	"Magnolia677",
	"Majash2020",
	"Maliepa",
	"MallardTV",
	"Maltazarian",
	"Mandarax",
	"Manzarene",
	"MapsMan",
	"MarcGarver",
	"Marcocapelle",
	"MarioJump83",
	"Mark Ironie",
	"Mark viking",
	"Markussep",
	"Markworthen",
	"Mary Mark Ockerbloom",
	"Masktapeisawesome",
	"Masonpatriot",
	"Masssly",
	"Master of Time",
	"Mathglot",
	"Mathieu ottawa",
	"Mathmo",
	"Matrix",
	"Matt Deres",
	"Mattbuck",
	"Matthewmayer",
	"Matthewrb",
	"Max24",
	"Mazewaxie",
	"MBlaze Lightning",
	"MC10",
	"Mclay1",
	"Mdaniels5757",
	"MDEire",
	"Me and",
	"Me, Myself, and I are Here",
	"MediaKyle",
	"Melonkelon",
	"Member",
	"Mesocyclonic93",
	"Metaviva",
	"Mgiganteus1",
	"Mhardcastle",
	"Mhhossein",
	"MiasmaEternal",
	"Michael Goodyear",
	"MichaelMaggs",
	"Micromesistius",
	"Microwave Anarchist",
	"MightyWarrior",
	"Mikael Häggström",
	"Mild Bill Hiccup",
	"Milo8505",
	"Milonica",
	"Miminity",
	"Minna Sora no Shita",
	"Minorax",
	"Miquonranger03",
	"MisterBee1966",
	"Mitch Ames",
	"MJL",
	"Mjquinn id",
	"Mkcaldwell",
	"Moe Epsilon",
	"Mojoworker",
	"Molly-in-md",
	"Morriswa",
	"Mortee",
	"Moscow Connection",
	"MrBauer24",
	"MRD2014",
	"MrDolomite",
	"MrE",
	"MrLinkinPark333",
	"MRSC",
	"Mrwojo",
	"Mscuthbert",
	"MSK",
	"Msrasnw",
	"Mtjannetta",
	"Muhandes",
	"Mushushu",
	"Muttnick",
	"Muéro",
	"Mvcg66b3r",
	"Mwiqdoh",
	"Mwwv",
	"MX Alt",
	"MZMcBride",
	"N2e",
	"Nableezy",
	"Nadzik",
	"Nagol0929",
	"Nahnah4",
	"Naraht",
	"Nardog",
	"Narenko",
	"Narky Blert",
	"Narom",
	"Narutolovehinata5",
	"Nat965",
	"Nathan Obral",
	"Nathan2055",
	"NE Ent",
	"NE2",
	"Nedia020415",
	"Neils51",
	"Neko-chan",
	"Neo139",
	"Neodop",
	"NeonMerlin",
	"Netherzone",
	"Netoholic",
	"Neutralhomer",
	"Neveselbert",
	"Newbiepedian",
	"Neøn",
	"Niagara",
	"NickCT",
	"Nickin",
	"Nickrds09",
	"Nigej",
	"NightWolf1223",
	"Nikolaih",
	"Nil NZ",
	"Nimbus227",
	"Ninjastrikers",
	"Nirinsanity",
	"Nirmaljoshi",
	"Nitesh003",
	"Nixleovel",
	"Nizil Shah",
	"Nkon21",
	"NoahRiffe",
	"Nohomersryan",
	"Noleander",
	"Nomader",
	"NonsensicalSystem",
	"Nontes",
	"NoobThreePointOh",
	"Northern Moonlight",
	"Northernhenge",
	"Not-cheesewhisk3rs",
	"NotAGenious",
	"NotTheFakeJTP",
	"NottNott",
	"Nova Crystallis",
	"NSH001",
	"Numbermaniac",
	"Nuvolet",
	"NyanThousand",
	"Nythar",
	"Nzdjb",
	"Obi2canibe",
	"Occono",
	"Ohconfucius",
	"Okashikunai",
	"Oklopfer",
	"Olaniyan Olushola",
	"Old Naval Rooftops",
	"Oldag07",
	"Oldiesmann",
	"Ollieinc",
	"Omnis Scientia",
	"Omphaloscope",
	"Onceinawhile",
	"Onco p53",
	"Onel5969",
	"Oosoom",
	"OpalYosutebito",
	"Opencooper",
	"Ophyrius",
	"Opm581",
	"Orange sticker",
	"OrangeDog",
	"Orangesclub",
	"Oronsay",
	"Osarius",
	"Ospalh",
	"Ost316",
	"Otr500",
	"Overthrows",
	"Owain",
	"Owais Al Qarni",
	"OwenBlacker",
	"P199",
	"Pachu Kannan",
	"Padres Hana",
	"Paine Ellsworth",
	"Paintspot",
	"Palmiped",
	"Palnatoke",
	"PamD",
	"Panamitsu",
	"PandaB31",
	"Paper9oll",
	"Paradoctor",
	"PARAKANYAA",
	"Partofthemachine",
	"Parutakupiu",
	"Pascal666",
	"Patient Zero",
	"Paul 012",
	"Paul2520",
	"Pavel Vozenilek",
	"Pbritti",
	"Pbrks",
	"PC78",
	"PCN02WPS",
	"Peaky76",
	"Pedantical",
	"PeeJay",
	"PEIsquirrel",
	"Pelmeen10",
	"Penale52",
	"Pennsy22",
	"Pentagon 2057",
	"PerfectSoundWhatever",
	"PersusjCP",
	"Pessottino",
	"Petecarney",
	"Peter Greenwell",
	"Peters01",
	"Peterwhy",
	"Petewarrior",
	"Pharaoh of the Wizards",
	"PharyngealImplosive7",
	"Phatom87",
	"Philafrenzy",
	"Philipnelson99",
	"Phoebe",
	"Phuzion",
	"Pigsonthewing",
	"Pineapple Storage",
	"Pkbwcgs",
	"PKT",
	"Plandu",
	"Plantdrew",
	"Plantsurfer",
	"Plasticwonder",
	"PleaseStand",
	"Ploni",
	"Pne",
	"PoliceSheep99",
	"PolishHamster",
	"Polo",
	"Polunbus",
	"Polyamorph",
	"Polygnotus",
	"Ponor",
	"Pontificalibus",
	"Ponydepression",
	"Popcornfud",
	"Pppery (alt)",
	"Praseodymium-141",
	"Prashanthns",
	"Pratap555",
	"Praxidicae",
	"Presidentman",
	"Prhartcom",
	"Primergrey",
	"Pro-anti-air",
	"ProcrastinatingReader",
	"Procrastineur49",
	"Prof tpms",
	"Project Osprey",
	"Proscribe",
	"Pruneau",
	"Pseudomonas",
	"Publeek",
	"PunjabiEditor69",
	"Purin475",
	"Purplebackpack89",
	"Q8682",
	"QianCheng",
	"Quadrupletime",
	"QuartierLatin1968",
	"QueenCake",
	"QueerEcofeminist",
	"Quentin X",
	"Quinntropy",
	"Quondum",
	"Qwerfjkl",
	"Qwerty Binary",
	"Qədir",
	"R. S. Shaw",
	"Racconish",
	"RachelTensions",
	"Racklever",
	"Radagast",
	"RadioFan",
	"RafaelS1979",
	"Raihanur",
	"Raladic",
	"RandFreeman",
	"RandomEditsForWhenIRemember",
	"Rangasyd",
	"Rankersbo",
	"Ratnahastin",
	"Ravenpuff",
	"Ravensfire",
	"Ravenswing",
	"Raydann",
	"Rayukk",
	"Razr Nation",
	"RCSCott91",
	"Rcsprinter123",
	"RealFakeKim",
	"Red Director",
	"Red Slash",
	"Red0ctober22",
	"Redalert2fan",
	"RedPanda25",
	"Redtigerxyz",
	"Reinoutr",
	"Relbats",
	"Remsense",
	"Reschultzed",
	"RetroCraft314",
	"Reubot",
	"Revi C.",
	"Rexogamer",
	"Reywas92",
	"RFBailey",
	"Rfc1394",
	"Rhindle The Red",
	"Rhododendrites",
	"Rich Smith",
	"RickyCourtney",
	"Rillian",
	"Rin",
	"Ringerfan23",
	"Rjwilmsi",
	"Rkieferbaum",
	"Rob Kam",
	"Robby",
	"Roberticus",
	"Robertjamal12",
	"RobertskySemi",
	"Robevans123",
	"Robwingfield",
	"Robynthehode",
	"Roc0ast3r",
	"Roches",
	"Rockfang",
	"Rodw",
	"Rogermx",
	"Rohini",
	"RolandR",
	"Roller26",
	"Romanm",
	"Ron Oliver",
	"Rorschach",
	"Royiswariii",
	"Rpyle731",
	"Rrburke",
	"Rrius",
	"Rsocol",
	"Rsrikanth05",
	"Rublov",
	"RudolfSchreier",
	"Rusty Cat",
	"Rwlesses",
	"Rye 212",
	"Ryūkotsusei",
	"S Marshall",
	"S.A. Julio",
	"SafariScribe",
	"Sagotreespirit",
	"Sahaib",
	"Salmon of Knowledge",
	"Salvidrim!",
	"Sam S",
	"Sam Sailor",
	"SamB",
	"Sameboat",
	"Samee",
	"SamuelNelsonGISP",
	"Sanfranman59",
	"Sarah Canbel",
	"Sarefo",
	"Satellizer",
	"Sauzer",
	"SaxTeacher",
	"Sbb",
	"Scarykitty",
	"Sceptre",
	"Schierbecker",
	"SchmuckyTheCat",
	"SchreiberBike",
	"ScienceDawns",
	"Scope creep",
	"Scotty.tiberius",
	"Scourgezoned",
	"Sdsds",
	"Sean.hoyland",
	"Seasider53",
	"Sebbog13",
	"Seidenstud",
	"Selbsportrait",
	"Sellyme",
	"Semmendinger",
	"Seppi333",
	"SerChevalerie",
	"Serial Number 54129",
	"Serialjoepsycho",
	"Set theorist",
	"SFGiants",
	"Sgroey",
	"Shawn à Montréal",
	"Sheep8144402",
	"Shenme",
	"Shhhnotsoloud",
	"Shibbolethink",
	"Shocksingularity",
	"Shoerack",
	"Shotgunheist",
	"Shovon76",
	"Shwabb1",
	"Siawase",
	"Sid95Q",
	"Sillyfolkboy",
	"SilverStar54",
	"Simon Burchell",
	"SimplyLouis27",
	"Sink Cat",
	"Sir Joseph",
	"Sitush",
	"Sjones23",
	"Skarmory",
	"Skarz",
	"Skilgis1900",
	"Skipple",
	"Slasher-fun",
	"Slazenger",
	"Slowking Man",
	"Slowmover",
	"Sm8900",
	"Smallangryplanet",
	"Smartyllama",
	"SmartyPants22",
	"SMcCandlish",
	"Smeagol 17",
	"Smerus",
	"Smooth O",
	"SMP",
	"Smuckola",
	"Snek01",
	"Snowdawg",
	"Snowmanonahoe",
	"Snowmanradio",
	"SocietyBox",
	"Sock",
	"Solidest",
	"Somnifuguist",
	"Soni",
	"Sophisticatedevening",
	"SophisticatedeveningALT",
	"SounderBruce",
	"Spiderone",
	"Spiffy sperry",
	"Spike 'em",
	"SpikeToronto",
	"Spintendo",
	"Spiral6800",
	"Sporti",
	"Sportzpikachu",
	"SpragueThomson",
	"Sputink",
	"Spyder Monkey",
	"Sreejithk2000",
	"Srich32977",
	"Ssriram mt",
	"SSSB",
	"StAnselm",
	"Starcheerspeaksnewslostwars",
	"StargazerG",
	"Starship.paint",
	"Staryu",
	"Staticshakedown",
	"Steel1943",
	"StefenTower",
	"Stefán Örvar Sigmundsson",
	"Stephenjh",
	"Stevage",
	"Steve Quinn",
	"Stjn",
	"Straughn",
	"Streetr4",
	"Stryn",
	"Stuartyeates",
	"Stvbastian",
	"Subwaymuncher",
	"SUM1",
	"Suntooooth",
	"SuperHamster",
	"Surajr7",
	"Suriname0",
	"Svgalbertian",
	"Swpb",
	"Synoman Barris",
	"Synpath",
	"Taavi",
	"Tachs",
	"Tails Wx",
	"Tajotep",
	"Takamaxa",
	"Takipoint123",
	"TAnthony",
	"Tatupiplu",
	"Tazerdadog",
	"Tbhotch",
	"TCMemoire",
	"Teblick",
	"Techie3",
	"TedEdwards",
	"Teemu08",
	"Tenbergen",
	"TenthAvenueFreezeOut",
	"Tentinator",
	"Terrek",
	"ThaesOfereode",
	"ThatOneTechNerd",
	"The Duke of Nonsense",
	"The Eloquent Peasant",
	"The Equalizer",
	"The Grid",
	"The Knowledge Pirate",
	"The Midnite Wolf",
	"The Obento Musubi",
	"The Squirrel Conspiracy",
	"The Transhumanist",
	"The-Pope",
	"The359",
	"The9Man",
	"TheAustinMan",
	"TheBigJagielka",
	"Thebiguglyalien",
	"TheDoctorWho",
	"TheFrog001",
	"TheGEICOgecko",
	"TheHYPO",
	"TheKaphox",
	"TheLongTone",
	"TheManInTheBlackHat",
	"Theodor Langhorne Franklin",
	"ThePlatypusofDoom",
	"Thewolfchild",
	"TheZoodles",
	"ThiagoSimoes",
	"Thilio",
	"This is Paul",
	"This, that and the other",
	"Thomprod",
	"Threeohsix",
	"Timeshifter",
	"TiMike",
	"Timothytyy",
	"TinaLees-Jones",
	"Tingrin87",
	"Tintin1107",
	"Tinton5",
	"Tiredmeliorist",
	"Tiven2240",
	"TJRC",
	"Tktktk",
	"Tol",
	"Tolly4bolly",
	"Tom (LT)",
	"Tom Danson",
	"Tom.Reding",
	"Tomchiukc",
	"Tomer T",
	"Tompw",
	"Tony Tan",
	"Tonyfaull",
	"Tonymetz",
	"TonyStarks",
	"TonyTheTiger",
	"ToprakM",
	"Torchiest",
	"Torsodog",
	"Tpbradbury",
	"Trailblazer101",
	"Transgenderoriole",
	"Travisl",
	"Triesault",
	"Triptothecottage",
	"TrueCRaysball",
	"Tserton",
	"TU-nor",
	"TubularWorld",
	"Tucoxn",
	"TucsonDavid",
	"Tupsumato",
	"TurboGUY",
	"TutterMouse",
	"Tvx1",
	"Twinsday",
	"TwoTwoHello",
	"TylerBurden",
	"Tyw7",
	"Ubcule",
	"UDScott",
	"Uhai",
	"UKER",
	"Ukexpat",
	"ULPS",
	"Ultraodan",
	"UltrasonicMadness",
	"Ulubatli Hasan",
	"Un assiolo",
	"Underbar dk",
	"UnitedStatesian",
	"Urbanracer34",
	"Uruiamme",
	"Useddenim",
	"Usedtobecool",
	"Usernamekiran",
	"Usernamekiran (AWB)",
	"Utopes",
	"UW Dawgs",
	"Uziel302",
	"Vahurzpu",
	"Valorrr",
	"Vanderwaalforces",
	"Vanisaac",
	"Varnent",
	"Vashti",
	"VastV0idInSpace0",
	"VasuVR",
	"Vatsmaxed",
	"Velella",
	"Vensatry",
	"VerdictByLogic",
	"Vermont",
	"Vestrian24Bio",
	"Victor Lopes",
	"VIGNERON",
	"Vinegarymass911",
	"Vipinhari",
	"Vis M",
	"Vlad",
	"Voidxor",
	"Volcanoguy",
	"Volten001",
	"Voyaging",
	"Vozhan",
	"Vpab15",
	"VQuakr",
	"Vukky",
	"VulcanSphere",
	"Waacstats",
	"Waddie96",
	"Wagino 20100516",
	"Walkerma",
	"Wall Screamer",
	"Warren",
	"Warriorglance",
	"WeatherWriter",
	"WeWake",
	"Whoop whoop pull up",
	"Whywhenwhohow",
	"Widefox",
	"Wiiformii",
	"WikiAviator",
	"Wikieditor019",
	"WikiEditor50",
	"WikiOriginal-9",
	"Wikipedialuva",
	"Wikipedical",
	"WikipediholicRat",
	"Wikipediæ philosophia",
	"Wikipelli",
	"WildCherry06",
	"WildStar",
	"Wilfridselsey",
	"Wilhelmina Will",
	"William Avery",
	"William2001",
	"WilliamThweatt",
	"Wingman4l7",
	"WinstonDewey",
	"Wjhonson",
	"Wlmg",
	"WMSR",
	"Wolbo",
	"Womtelo",
	"Wongm",
	"WoodElf",
	"Worldbruce",
	"WormEater13",
	"WT79",
	"WWGB",
	"Wwwhatsup",
	"Wxtrackercody",
	"X201",
	"X96lee15",
	"XtraJovial",
	"Xurizuri",
	"Yabroq",
	"Yacàwotçã",
	"Yadsalohcin",
	"Yahya",
	"YBG",
	"Yeeno",
	"Yerevantsi",
	"Yerpo",
	"Yeshivish613",
	"Yodin",
	"Yogwi21",
	"Yoshi24517",
	"YoungForever",
	"Your Friendly Neighborhood Sociologist",
	"Ysangkok",
	"Yutsi",
	"Zachlp",
	"Zackmann08",
	"Zadora13",
	"Zakhx150",
	"Zalaraz",
	"Zanahary",
	"Zanoni",
	"Zarex",
	"Zefr",
	"Zeibgeist",
	"Zeng8r",
	"Zetud",
	"ZI Jony",
	"Zingarese",
	"Zippybonzo",
	"ZKang123",
	"ZLEA",
	"Zmbro",
	"Zntrip",
	"Zpb52",
	"Zppix",
	"Zxcvbnm",
	"Zxm92",
	"Zythe",
	"Zyxw",
	"~delta",
	"Île flottante",
	"Αρκάς",
	"Οἶδα",
	"Χ",
	"Векочел",
	"Викидим",
	"Милан Јелисавчић",
	"Шахматист2025",
	"أبو هشام",
	"علاء",
	"مصعب",
	"बडा काजी",
	"२ तकर पेप्सी",
	"আফতাবুজ্জামান",
}
